### ISSUE TITLE
assignment count mismatch: 2 = 1

### ISSUE THREAD

**Issue by chris-short** [jbarone/ghostToHugo#10]
```
chrisshort@cshort-mbp ~> go get github.com/jbarone/ghostToHugo
# github.com/spf13/hugo/parser
go/src/github.com/spf13/hugo/parser/frontmatter.go:55: assignment count mismatch: 2 = 1
```

**Comment by jbarone** [comment]
Hello @chris-short, could you tell me what version of Hugo you are using?

    $ hugo version

**Comment by jbarone** [comment]
I've just tested installing on a clean system. I think the issue may be the version of Hugo you are using. Could you please try to install with the `-u` option and let me know if that works for you 

    $ go get -u github.com/jbarone/ghostToHugo

**Comment by chris-short** [comment]
`chrisshort@cshort-mbp ~> go get -u github.com/jbarone/ghostToHugo
chrisshort@cshort-mbp ~> hugo version
Hugo Static Site Generator v0.21-DEV darwin/amd64 BuildDate: 2017-04-28T09:26:39-04:00`

**Comment by chris-short** [comment]
Your assumption was correct. Thanks!
