### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by danielkdewar** [jbarone/ghostToHugo#11]
Regardless of the ghostToHugo command, I am getting command not found:

```
danieldewar filmaday $ ghostToHugo -dateformat /Users/danieldewar/documents/filmaday/filmaday.ghost.2017-05-28.json
-bash: ghostToHugo: command not found
```
Do I have my command format correct? I've looked up the documentation and I can see where I would be wrong.

**Comment by jbarone** [comment]
Hello @danielkdewar 

It looks like you are using the old syntax there. I hadn't updated the [README](https://github.com/jbarone/ghostToHugo/blob/master/README.md) in a while, so I went ahead and did that, and included examples. Please take a look and see if the new one helps.

Secondly, the `command not found` is saying that bash is unable to locate the binary. This could be happening for a few different reasons. Most likely though, your `$PATH` variable doesn't include `$GOPATH/bin` you can check this by executing with the full path. Should be something like

    $ ~/go/bin/ghostToHugo -h

If that works then you just need to update your path to include `$GOPATH/bin`.
