### ISSUE TITLE
hugolib: exit status 1

### ISSUE THREAD

**Issue by lyoshenka** [jbarone/ghostToHugo#12]
Getting the following error when trying to install:

```
$ go get -u github.com/jbarone/ghostToHugo
# cd /home/grin/go/src/github.com/spf13/hugo; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to rebase against.
See git-pull(1) for details.

    git pull <remote> <branch>

<LONG PAUSE HERE>
package github.com/spf13/hugo/hugolib: exit status 1
```

Let me know if it would help to provide any details about my setup.

**Comment by jbarone** [comment]
Looks like you have changed something in Hugo. You can either revert those changes or drop the `-u` option so that it doesn't try to update.

If it's still giving you problems, then try adding `-v` option and share the output here.

**Comment by lyoshenka** [comment]
I figured it out. I had a global gitattributes file that performs LF normalization in text files, and it had trouble updating since some files have Windows-style line endings.

Anyway, the problem was on my end. Thanks for your help.

**Comment by jbarone** [comment]
That is great to hear that it worked out. You did inspire me though, so the lib is now vendored, and I am now supplying pre-build binaries on the releases page.

**Comment by Kaligule** [comment]
@jbarone It would be very usefull to mention the prebuilt binaries in the README. I think there are a great idea.

**Comment by jbarone** [comment]
Thanks @Kaligule, It apparently slipped my mind. I've updated the README.

**Comment by Kaligule** [comment]
Very helpfull, thank you @jbarone
