### ISSUE TITLE
Can't import, "unmarshal string" error

### ISSUE THREAD

**Issue by bgiesing** [jbarone/ghostToHugo#14]
Throws this error, not sure why:

```bash
2017/11/04 18:08:42 Error processing Ghost export: json: cannot unmarshal string into Go struct field posttag.id of type int
```

**Comment by jbarone** [comment]
Sorry you're having an issue. Could you do my a favor and post your `post_tags` section of your json export? That error message is telling me that you have and id field that is quoted as a string, and it should be an unquoted number.

**Comment by bgiesing** [comment]
@jbarone it crashed my computer trying to open the export I can't check, here's the whole file. https://gateway.ipfs.io/ipfs/QmXYW16qQNEFRv2gCha1F1X6z1NfosfsXRME8xHVmp7BQt/brandon-giesing.ghost.2017-11-04.json

**Comment by jbarone** [comment]
Interesting, it appears that your export is using a hex string as IDs. That must be something new. I will get an update in to solve this, but it may not be tonight.

Also, appreciate you sharing this export, I will get this working for you.

**Comment by jbarone** [comment]
@bgiesing I've pushed a new update that seems to have fixed importing for your export. Just get the latest version and you should be good to go:

```
$ go get -u github.com/jbarone/ghost2Hugo
```

Let me know if you have any other issues.

**Side Note**: looks like some of your markdown (specifically links) isn't quite right and may need to be edited to display the way you want.
