### ISSUE TITLE
Fails to migrate images

### ISSUE THREAD

**Issue by jloh** [jbarone/ghostToHugo#15]
I've got a post that has the following markdown:

```
some text up here

![image](/content/images/2017/12/image.png)

some more text down here
```

After the migration the image markdown doesn't seem to make it into the hugo export.

Using Ghost 1.19.2 and the latest ghostToHugo.

**Comment by jbarone** [comment]
what is the output you get?

**Comment by jloh** [comment]
It drops the image entirely as if it was never there. Ends up something like this:

```
some text up here



some more text down here
```

Basically just an extra blank line.

**Comment by jbarone** [comment]
@jloh I have fixed the issue, and have cut a new release. Please let me know if you have any other issues.

**Comment by tareefdev** [comment]
Hi, I'm sorry to reopen this again, but I have the same problem here:

`![buddah](/content/images/2017/08/buddah.jpg)`

the previous link seems broken when I tried to make it:

`/hugo/content/images/2017/08/buddah.jpg`

it works. From `config.toml`:

`baseURL = "https://example.com/hugo/public"`

**Comment by jbarone** [comment]
sorry @tareefdev, I don't quite follow your question here. Is the markdown snippet what `ghostToHugo` created? Because, it is designed to strip out the `/content`. I would expect it to be

`![buddah](/images/2017/08/buddah.jpg)`

If that is not the case, then please open up a new issue.

**Comment by tareefdev** [comment]
Thanks, @jbarone yep the markdown snippet generated by `ghostaToHugo`.. So what other options I have here?

**Comment by jbarone** [comment]
@tareefdev please open a new issue, and provide me the version of Ghost that you exported
