### ISSUE TITLE
The script keeps images urls without changing

### ISSUE THREAD

**Issue by tareefdev** [jbarone/ghostToHugo#16]
I have the following image in my ghost blog:

`https://blog.example.com/content/images/2017/08/buddah.jpg`

After executing the script (v0.2.1) on json exported file from a ghost (v2.0.3), I got the following markdown:

`![buddah](/content/images/2017/08/buddah.jpg)`

This happens to all images and no one display on my new hugo blog. Although if I manually get rid of `/content` from the previous link, the image appears.

**Comment by jbarone** [comment]
Looks like ghost has changed the exports again. This is going to take me some time to update.

**Comment by tareefdev** [comment]
Maybe at this time, I'll use `sed` to do recursive search and replace in my files. BTW thanks for your great work here :)

**Comment by jbarone** [comment]
I'm looking at it a little more and realized that the version difference isn't your issue, would you be willing to provide you export? I could create a one off for you, or you could just go the `sed` route.

Seems I am stripping `/content` from cover images, but not in the content, so I will need to fix that, but updating for the new version is a bigger task.

**Comment by tareefdev** [comment]
Hi @jbarone thanks for your offer, I was able to do a search and replace using Emacs, now everything work, anyway the script helps me a lot, so thanks again.

**Comment by jbarone** [comment]
Awesome, I'm glad you got it working.

**Comment by tareefdev** [comment]
Hey @jbarone I have a question. In ghost there are two types of images:

- The one which you can add by clicking on the settings gear, this image just appears at the post's head.
- Inline images, those inserted in the post body. 

As I see the script doesn't export the post's image to the metadata section. For example, see the following post's metadata:

```
+++
author = someone
categories = tech
date = 2017-08-24T21:10:18Z
description = just a post
draft = false
slug = "new-post"
tags = ["tech"]
title = "A new post"

+++
```

What I I expect is another meta called `image` to show the post header image.

**Comment by jbarone** [comment]
Hmm it actually should be adding that one. Is the image declared in the post you're referring to?

you should see a tag in that post like this:

```
{
    ...
    "image": "/content/image/file.jpg",
    ....
}
```

**Comment by jbarone** [comment]
sure thing, you can email it to me (joshua.barone AT gmail)

**Comment by tareefdev** [comment]
oh thanks :)

**Comment by jbarone** [comment]
New release binaries are up (v0.2.2) it will handle the cover image issues, you will still need to `sed` the `/content` url for content though.

**Comment by tareefdev** [comment]
Great! thanks
