### ISSUE TITLE
Tool does not work with Ghost 3.x export

### ISSUE THREAD

**Issue by jbfriedrich** [jbarone/ghostToHugo#26]
**Describe the bug**
When running ghostToHugo with a Ghost 3.x export file, the tool quits with the error message `2019/11/06 15:53:06 Error processing Ghost export: not at beginning of value`.

**Version of Ghost**
3.0

**To Reproduce**
Run `../ghostToHugo ~/Downloads/jason-friedrich.ghost.2019-11-06-13-59-32.json` and immediately receive the error message.

**Expected behavior**
Same export of posts and settings as with the Ghost 2.x backup file.

**Comment by jbarone** [comment]
Thanks for the report. I'm currently doing a rewrite to update some things, I will add this to that effort as well.

**Comment by jbfriedrich** [comment]
Thanks for the quick reply. Sounds great! 😃. Do you already have a time frame in mind? I am currently moving my blog and all that is missing is migrating the content. Just curious as I am anxious to complete my move. 

Thanks for this great tool! I tried to walk through some code to send a PR, but my brain seems to be unable to parse Go code 🙂.

**Comment by jbarone** [comment]
$JOB is keeping me pretty busy right now, but I'm planning to have something for early next week to push out.

**Comment by jbfriedrich** [comment]
Thanks for the feedback, appreciate it! Then I’ll hold off and wait. Thanks again!

**Comment by jbarone** [comment]
@jbfriedrich v0.4.0 is out. I didn't change much of the parser, it still worked agains the ghost v3 exports that I created to test with. If you still have issues, please let me know.

**Comment by jbfriedrich** [comment]
Thanks @jbarone! I will test it with my export in the last couple of days. If i dont update this thread, everything worked smoothly. Thanks for the update!
