### ISSUE TITLE
cannot unmarshal string into Go value of type ghosttohugo.meta

### ISSUE THREAD

**Issue by RealCodeTips** [jbarone/ghostToHugo#28]
**Describe the bug**
When running the script the following error is returned

```
Importing...
FATAL 2020/01/25 16:23:26 Error opening export: json: cannot unmarshal string into Go value of type ghosttohugo.meta
```

**Version of Ghost**
3.1.1

**To Reproduce**
1. Exported the json file from the Lab section
2. Ran `./ghostToHugo --dateformat "2006-01-02T15:04:05.000Z" -f -p project export.json`
3. See error

**Expected behavior**
Import would run successfully. 

**Additional context**
From a little bit of debugging this is happening the second time `meta` is called.

**Comment by jbarone** [comment]
Interesting. `meta` should only be called once. But, I think I have an idea what is happening. I’ll be able to take a look a little later today.

**Comment by RealCodeTips** [comment]
Unfortunately, I don't have my preferred IDE on my personal laptop so can't debug it very well 👍 

I got around it by cloning the repo and just commenting out the `return err` statement in `info.go`.

**Comment by jbarone** [comment]
Would you be willing to share your export with me? I can't seem to recreate the issue on my end.

**Comment by RealCodeTips** [comment]
Honestly, I'd have to inspect it first as I don't know what's included in the export.

In the mean time, if it helps, I decoded the data to an `interface{}` if `c.info.meta` has already been populated and this is the part that caused the error:

```
Tok: meta
decoded: [{"data":{"id":"<20191217180236.1.C62F3D5944D0AD7F@codetips.co.uk>","message":"Queued. Thank you."}}]
```

**Comment by RealCodeTips** [comment]
Which seems to be part of an "emails" section 🤔 

```
"emails":[{"id":"5df9183ca910f707670999ce","post_id":"5df28727510aec76740c6092","uuid":"354532a9-d18a-4f8e-998a-346ba9cb11fc","status":"submitted","error":null,"error_data":"[]","meta":"[{\"data\":{\"id\":\"<20191217180236.1.C62F3D5944D0AD7F@codetips.co.uk>\",\"message\":\"Queued. Thank you.\"}}]","stats":"{\"delivered\":0,\"failed\":0,\"opened\":0,\"clicked\":0,\"unsubscribed\":0,\"complaints\":0}","email_count":44,
```

I have a feeling this is because of the new Ghost V3 set-up, where it can now manage emails to users etc....

**Comment by jbarone** [comment]
Ugh, that was what I suspected.

**Comment by RealCodeTips** [comment]
If it helps, I got around it by adding a condition to check if `c.info.meta` has already been populated.

```
if c.info.meta.ExportedOn == 0 && c.info.meta.Version == "" {
    err = decoder.Decode(&a)
}
```

Honestly, the import/export/backup process on Ghost is one of the reasons I'm moving away.

**Comment by jbarone** [comment]
I think I can make it cleaner. Just scratching my head over here. If there is any sensitive info in the export, it would be in the `settings` section. If you strip that out, should be safe to send my way.

**Comment by jbarone** [comment]
@RealCodeTips I have a candidate fix, would you be willing to test it for me? Which OS are you running on?
