### ISSUE TITLE
Import Not Working with Ghost 3.35.5

### ISSUE THREAD

**Issue by egoebelbecker** [jbarone/ghostToHugo#29]
**Describe the bug**
I'm trying to run an import with a JSON file from v3.35.5. (It's a Ghost Pro Site.)

I'm getting this error:

FATAL 2020/10/17 21:47:36 Error opening export: json: cannot unmarshal string into Go value of type ghosttohugo.meta

I've pulled down the latest source and built from GitHub, since the last release looks to be older. Same error.

**Version of Ghost**
3.35.5

**To Reproduce**
ghostToHugo -v --location "America/New_York" -p ~/src/ericgoebelbecker.com/ export.json

**Link to export**
https://drive.google.com/file/d/1W3SocS5OOTn40MSYx_Ne674NL1i92eww/view?usp=sharing

**Comment by jbarone** [comment]
Sorry for not responding sooner. I am looking into this. A lot has changed on both ghost side and hugo side, I'm trying to make them match back up. I hope to have a new version up soon.

**Comment by egoebelbecker** [comment]
Much appreciated! I'm hoping to migrate over before my account renews, but I've got some time left. I'd be happy to help with testing.

**Comment by jbarone** [comment]
@egoebelbecker I'm still working on it. I don't have it release ready, but I do think I have it working against the export you shared. If you would like to test it, could you please send me an email and tell me what OS you're running on. I can send you a build to try out. Thanks.

**Comment by BirkhoffLee** [comment]
I'm on Ghost 3.38.3 looking to migrate to Hugo. I'm willing to help out for testing too!

**Comment by jbarone** [comment]
@BirkhoffLee Excellent! What I could really use for testing right now is more example exports. If you're willing to share yours with me, that would help a lot. Feel free to shoot me an email if that works for you. Thanks.

**Comment by MarcoZehe** [comment]
I am also interested in a migration. Let me know if you need any more exports. 👍

**Comment by jbarone** [comment]
@MarcoZehe & @BirkhoffLee this should all be resolved with the latest version I just released.
