### ISSUE TITLE
Do you have plans to support ghost export file format v006 (Ghost v0.9) ?

### ISSUE THREAD

**Issue by tovare** [jbarone/ghostToHugo#3]
Hi,
Attempting to convert my blog causes an errot.

2016/08/09 08:23:08 Error processing Ghost export: json: cannot unmarshal string into Go value of type int64

It looks like ghost has updated it's file format stopped using milliseconds for timestamps in several fields:

```
{
    "db": [{
        "meta": {
            "exported_on": 1470745100993,
            "version": "006"
        },
        "data": {
            "posts": [{
                "id": 2,
                "uuid": "d7c71be9-d9ae-44bb-ad4b-aba722dade3d",
                "title": "2008",
                "slug": "2008",
                "markdown": "  <markdown content here>",
                "image": "/content/images/2015/01/IMG_3474-1.jpg",
                "featured": 0,
                "page": 0,
                "status": "published",
                "language": "en_US",
                "meta_title": " meta title here",
                "meta_description": " descripion here",
                "author_id": 1,
                "created_at": "2015-02-01 02:12:37",
                "created_by": 1,
                "updated_at": "2016-06-19 13:35:33",
                "updated_by": 1,
                "published_at": "2008-08-18 10:00:00",
                "published_by": 1,
                "visibility": "public",
                "mobiledoc": null
            }

```

**Comment by jbarone** [comment]
Thanks for reaching out, I was not aware that they changed DB versions again. 

- Can you please tell me what version of ghost you are using?
- Could you provide me with a sanitized copy of the export, to verify my fixes?

**Comment by tovare** [comment]
Hi,
Here´s a dump. The version is Ghost 0.9.0 

[tov-are-jacobsen.ghost.2016-08-09.json.zip](https://github.com/jbarone/ghostToHugo/files/409802/tov-are-jacobsen.ghost.2016-08-09.json.zip)

**Comment by jbarone** [comment]
Excellent, thanks. I will work on a fix for this.

**Comment by tovare** [comment]
great :-)

**Comment by jbarone** [comment]
@tovare I've added a new command line option ("-dateformat") that will allow you to specify a date format to use when processing the export. In your case you would use `-dateformat "2006-01-02 15:04:05"`, which results in the following command:

    $ ghostToHugo -dateformat "2006-01-02 15:04:05" tov-are-jacovsen.ghost.2016-08-09.json

Please let me know if you have any more issues.
