### ISSUE TITLE
Building errors with latest Go and current main branch on macOS Big Sur

### ISSUE THREAD

**Issue by MarcoZehe** [jbarone/ghostToHugo#30]
**Describe the bug**
When trying to build GhostToHugo via Go, I get the following error output:

```
cannot find package "github.com/jdkato/prose/transform" in any of:
	/usr/local/go/src/github.com/jdkato/prose/transform (from $GOROOT)
	/Users/marco/go/src/github.com/jdkato/prose/transform (from $GOPATH)
# cd /Users/marco/go/src/github.com/rwcarlsen/goexif; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/rwcarlsen/goexif/exif: exit status 1
# cd /Users/marco/go/src/github.com/nicksnyder/go-i18n; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/nicksnyder/go-i18n/v2/i18n: exit status 1
```

**Version of Ghost**
3.40, but that's not even at play yet here.

**To Reproduce**
1. Install current Go 1.15.4.
2. Run `go get -u github.com/jbarone/ghostToHugo`.

**Expected behavior**
GhostToHugo should build.

**Additional context**
MacOS 11.1 on an M1 chip. But the Go version is the current 1.15 release, which is still Intel-based and runs under Rosetta 2, not the 1.16Beta1 which is available as ARM64 build.

**Link to export**
N/A

**Comment by jbarone** [comment]
Can you try installing using this command:

`GO111MODULE=on go get github.com/jbarone/ghostToHugo@latest`

**Comment by MarcoZehe** [comment]
This installation worked. I also got a directory structure created, and a suggestion to download a theme and how to start Hugo with that theme.

However, I am noticing two thing:

1. I usually have an excerpt in my posts, and this also gets exported to the JSON file. I saw this when I tried an exporter that exported kind of yaml/Markdown with Jekyll-style front matter files. However, your exporter seems to completely ignore those excerpts. I thought they'd go into the description of each post's Markdown file/TOML header.
2. When running Hugo with the exported file and the downloaded theme, I got the following at the top of the output, which you might want to be aware of:
```
Start building sites … 
WARN 2020/12/31 17:05:46 Page.Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2020/12/31 17:05:46 Page.RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ .RelPermalink }}{{ end }}

                   | EN   
-------------------+------
  Pages            | 592  
  Paginator pages  |   0  
  Non-page files   |   0  
  Static files     |  15  
  Processed images |   0  
  Aliases          |   0  
  Sitemaps         |   1  
  Cleaned          |   0  
```

**Comment by jbarone** [comment]
Glad the installation worked, I'll update the README with those new instructions.

1. I don't think I've encountered the excerpt before. If you could share your export with me I'll be happy to take a look. Better yet, I'll close this issue, could you open a new issue for the missing excerpt and we can work it there?

2.  This is a known issue, the suggested theme is one that is out of date and not being updated anymore. I've included it because it matches the instructions of the official Jekyll import command.

**Comment by jbarone** [comment]
@MarcoZehe  No need for the new issue or the export. I've identified what needs to happen and will have a fix pushed shortly. Thanks for alerting me to this.
