### ISSUE TITLE
Add option for page bundles

### ISSUE THREAD

**Issue by sebdanielsson** [jbarone/ghostToHugo#31]
Would be neat with an option to automatically create a [page bundle](https://gohugo.io/content-management/page-bundles/) for all posts. I converted all of my posts to leaf bundles with this shell script but it would be even better to have this built in.

For example you could have the following options:
--leaf              use this option to create a leaf bundle for each post
--branch        use this option to create a branch bundle for each post

```
for x in ./*.md; do
  mkdir "${x%.*}" && mv "$x" "${x%.*}/index.md"
done
```

**Comment by jbarone** [comment]
This is very interesting. I'll look into this for sure.
