### ISSUE TITLE
How to access my converted MD files? 

### ISSUE THREAD

**Issue by exist2021** [jbarone/ghostToHugo#34]
Hello, 

I manage to import my 984 blog posts, but now I don't know how to see these MD files. I don't really want a Hugo site, all I wanted was to convert JSON to MD. Could you please help? 

![Screenshot 2021-08-03 at 5 24 15 PM](https://user-images.githubusercontent.com/83490199/128019783-86391dc3-1ffe-46d5-8580-d16da5dded3d.png)

**Comment by jbarone** [comment]
Hello @exist2021 

When you convert the site to Hugo, the `newhugosite` folder will be laid out according to Hugo conventions. This means that your markdown files will be in `newhugosite/content` folder, with post type entries being in the `post` folder inside content.

**Comment by exist2021** [comment]
Ok. I am sorry not a programmer. But how do i convert the site to Hugo. Your read me files ends abruptly I felt. All I have is the screenshot I shared.

**Comment by exist2021** [comment]
I did, but I got this command not found. Thanks for the help, really appreciate it. Let me know how to proceed further. 

![Screenshot 2021-08-03 at 7 48 24 PM](https://user-images.githubusercontent.com/83490199/128032024-e33469a4-1e59-41f1-b21a-18d8fc452fb9.png)

**Comment by jbarone** [comment]
Ah okay, seems you don't have Hugo installed then. You can find the instructions to get that setup on the Quick Start page on Hugo's site https://gohugo.io/getting-started/quick-start/

**Comment by exist2021** [comment]
Ah! Will do

**Comment by jbarone** [comment]
Hmmm that sounds like it's having an issue with some short code inside that particular file. Would you be willing to share your export with me? I can take a look and see if I can figure out what is going on

**Comment by exist2021** [comment]
If you mean my ghost JSON file, here is the file https://www.dropbox.com/sh/a7zvdcfxb4pm3ok/AAA6SLG7THtMDaqiRqIlzeCZa?dl=0

**Comment by jbarone** [comment]
I grabbed it, if you want to delete it or stop sharing it. I'll check it out and let you know what I discover

**Comment by exist2021** [comment]
No worries just one of the two 10 year old blogs I am trying to shift from Ghost. 

Do let me know when you have the solution.

**Comment by jbarone** [comment]
Looks like you have some links in the image captions on that particular post. If you go remove the anchor tags from the caption section, the site builds fine.

**Comment by exist2021** [comment]
There are 984 posts. Which particular post are you referring to? Can you remove the same for me? Or show me which one. Sorry, if I am taking too much of your time. Happy to pay for this if I can afford. :)

**Comment by jbarone** [comment]
It's the one listed when you try to run `hugo server`. It's `newhugosite/content/post/interview-with-mary-dsouza-sequiera-indias-first-female-olympian-from-bandra.md`

But here is a modified version of it for you https://www.dropbox.com/s/agy47ml6ux7ii7i/interview-with-mary-dsouza-sequiera-indias-first-female-olympian-from-bandra.md?dl=0

**Comment by exist2021** [comment]
I removed that file from my JSON file but now I am not able to run the ghosttohugo command. 
![Screenshot 2021-08-04 at 12 42 22 AM](https://user-images.githubusercontent.com/83490199/128072736-f5580565-3f42-49ea-a7b3-3ae384986b88.png)

**Comment by jbarone** [comment]
I'm guessing from this screenshot, this is a different system than what you originally ran on. If you're running a newer version of go installed then you may need to change your install command a bit

```bash
$ go install github.com/jbarone/ghostToHugo@v0.5.3
```

This should download, build, and install `ghostToHugo` in your `$GOPATH/bin` folder. If it still doesn't work after running the above command, try the following

```bash
$ ~/go/bin/ghostToHugo
```

I hope that helps you. Unfortunately I didn't do anything to make this super user friendly, as my original intent was just to scratch my own itch and convert my old blog. If this is still not working right, I do have some pre-built version on the release page here. If you macbook-air is one with the m1 chip I can try and do a build specifically for you as well.

**Comment by exist2021** [comment]
It is the same system, I have just one system for now. I am not able to do the `ghostToHugo` command. 

But I did update my mac to 11.5.1 Big Sur.  That is the only change that has happened. I am not sure if ghostToHugo is installed even after executing this `GO111MODULE=on go get github.com/jbarone/ghostToHugo@latest` Check screenshot. 
![Screenshot 2021-08-04 at 12 42 22 AM](https://user-images.githubusercontent.com/83490199/128147559-63d54ef0-dcbc-469a-ade1-f28413aa7744.png)

**Comment by jbarone** [comment]
Try doing this:

```bash
% export PATH=$PATH:$GOPATH/bin

% ghostToHugo -h
```

**Comment by exist2021** [comment]
Same issue after executing the command

![Screenshot 2021-08-04 at 4 58 32 PM](https://user-images.githubusercontent.com/83490199/128173270-d62f0701-3222-4bd0-a38c-73604a6c8606.png)

**Comment by jbarone** [comment]
Excellent!

So the tool is designed to create a new folder to hold the site, by default it calls it `newhugosite` and puts it into the current folder. You can tell it where to put it, or overwrite one that was already converted using the different options. You can see what options are available by using the `-h` flag: 

```
$ ~/go/bin/ghostToHugo -h
```
To specify where to put it, you would use the `-p` option:

```
$ ~/go/bin/ghostToHugo -p mysite /Users/manojnayak/Downloads/bandra-info.ghost.2021-08-03-18-43-58.json
```
This will create a folder called `mysite` and setup the converted hugo site there. (swap that out with the path to wherever you want to create it)

And finally to overwrite a folder with the export use the `-f` option.

**Comment by exist2021** [comment]
ok, I am close to getting this. Imported my 983 posts, but there is some error when running `hugo server --theme=herring-cove` Check screenshot.
![Screenshot 2021-08-06 at 4 44 40 PM](https://user-images.githubusercontent.com/83490199/128503364-7a7abc77-bb1f-475d-8733-5bafeb49a261.png)

**Comment by jbarone** [comment]
You need to install the theme that you want to use. If you were just following the example instructions, you forgot to clone the theme first. 

From what I can tell though, the import seems to have worked, so I'm going to go ahead and close this issue. If you need more help in getting Hugo up and running, I suggest you reach out to them on their discourse. They are really good at helping https://discourse.gohugo.io/

**Comment by exist2021** [comment]
Ah ok! Thanks so much!
