### ISSUE TITLE
Location option doesn't work on Windows

### ISSUE THREAD

**Issue by teejo75** [jbarone/ghostToHugo#36]
Using the option `-l "Australia/Brisbane"` with the latest Windows binary throws an error:
`FATAL 2021/10/01 19:19:15 Error loading location Australia/Brisbane: The system cannot find the path specified.`

I've tried running it elevated, but get the same error.

The Linux binary works fine.

**Comment by jbarone** [comment]
That is a super weird one. The timezone locations are loaded from the host OS, I believe. I need to look into Windows, and see if I can figure out what is going on there.

**Comment by jbarone** [comment]
Oh wow, seems I'm wrong, and things work differently on Windows. Okay so this appears to be a known issue, on windows systems where Go isn't installed (which I'm assuming is the case). I'll be happy to do a new build for you with the timezone data included. Would you be willing to test it for me before I add it to the release page?

**Comment by jbarone** [comment]
[ghostToHugo.exe.zip](https://github.com/jbarone/ghostToHugo/files/7267096/ghostToHugo.exe.zip)

If you could please give that a go and let me know if that works for you, I'd appreciate it. I've embedded the timezone info into it, so should work.

**Comment by teejo75** [comment]
Yes, it works perfectly. Thanks for the super fast response!

**Comment by jbarone** [comment]
Awesome! Thanks for letting me know about this. I wasn't aware this could be an issue.
