### ISSUE TITLE
Drafts don't carry over created_at time

### ISSUE THREAD

**Issue by edude03** [jbarone/ghostToHugo#4]
Thanks for the tool, I was able to easily migrate from Ghost to Hugo with it.

After importing I noticed that my drafts had a published at time of 1969 which makes me assume something somewhere tried to parse the published_at time of the post (null for drafts) and is using `null.to_date` as the published date. 

Looking here https://github.com/jbarone/ghostToHugo/blob/master/lib/ghost/ghost.go#L74-L88 it seems that this is the case. 

Would you consider doing something akin to `published_at: published() || created_at()`?

**Comment by jbarone** [comment]
@edude03 That's a great idea. I'll be happy to get that added in for you.
