### ISSUE TITLE
ghostToHugo command not found in WSL Ubuntu 

### ISSUE THREAD

**Issue by SasikaA073** [jbarone/ghostToHugo#41]
**Describe the bug**
I ran to this error, "ghostToHugo: command not found" but the "go install" command ran without giving in any errors. I ran this in WSL Ubuntu in Windows 11.

**Version of Ghost**
Ghost-CLI version: 1.21.0

**To Reproduce**

sasika@wsl :~$ cd ghostToHugo
sasika@wsl :~/ghostToHugo$ ghostToHugo export.json
> ghostToHugo: command not found
sasika@wsl :~/ghostToHugo$ go install
sasika@wsl :~/ghostToHugo$ ghostToHugo export.json
> ghostToHugo: command not found
sasika@wsl :~/ghostToHugo$ GO111MODULE=on go get github.com/jbarone/ghostToHugo@latest
> go get github.com/jbarone/ghostToHugo@latest: can't request explicit version of path in main module
sasika@wsl :~/ghostToHugo$ ghostToHugo --help
> ghostToHugo: command not found

**Expected behavior**
I wanted to run this command without getting any errors. 
"ghostToHugo export.json"

**Comment by jbarone** [comment]
`go install` should install into your `$GOPATH/bin` folder. Could you check to see if it's there, and that folder is part of your `$PATH`. If it's not in your path you can try to invoke directly

```bash
$ $GOPATH/bin/ghostToHugo -h
```

Optionally, you can try to install using 

```bash
$ go install github.com/jbarone/ghostToHugo@latest
```
