### ISSUE TITLE
Import stops after 3 posts

### ISSUE THREAD

**Issue by jchatard** [jbarone/ghostToHugo#5]
Hi,

I just tried this import program, currently hosted in Ghost platform.

Obviously I have more posts.

The meta version of the export says:

```json
{
  "db": [
    {
      "meta": {
        "exported_on": 1476365680877,
        "version": "009"
....
```

Anything I don't get?

Thank you!
Jérémy

**Comment by jbarone** [comment]
That's super odd. Would you be willing to share your export with me?

**Comment by jchatard** [comment]
Yeah sure, even though it's nothing really private, I can send you a link to get the export, via mail for example?

**Comment by jbarone** [comment]
cool send it too joshua(at)caveconfessions(dot)com

**Comment by jbarone** [comment]
okay, I'm seeing the issue. I'll dig into this and update here when I figure something out.

**Comment by jbarone** [comment]
What a fun problem you found for me. I've narrowed it down. It appears the way I was handling tags is what was causing the issue. I should have a fixed version up for you in about an hour.

**Comment by jchatard** [comment]
Awesome! 😍

**Comment by jbarone** [comment]
Took less time than I thought. 😄 Let me know if you have anymore issues with it.

**Comment by jchatard** [comment]
Rock 'n' roll! 😸 

Thank you so much for the insanely fast fix!
