### ISSUE TITLE
undefined: hugolib.NewPage

### ISSUE THREAD

**Issue by Chealion** [jbarone/ghostToHugo#7]
When running `go get github.com/jbarone/ghostToHugo`, I receive the following error:

    chealion@~ % go get github.com/jbarone/ghostToHugo
    # github.com/jbarone/ghostToHugo/lib/hugo
    Documents/go/src/github.com/jbarone/ghostToHugo/lib/hugo/hugo.go:75: undefined:  hugolib.NewPage

I did remove everything in `src` and `pkg` directories to clear things out just in case and then tried on a freshly made Ubuntu VM.

Do I need to downgrade my copy of Go, or was there a change in the `hugolib` dependency?

Go 1.7.4
Reproduced on Mac OS X and Ubuntu 14.04

**Comment by jbarone** [comment]
It looks like the dependancy `hugolib` has indeed changed. I will update `ghostToHugo` and push the changes.

**Comment by jbarone** [comment]
The code has been updated. Please let me know if you have anymore issues. Thanks.

**Comment by Chealion** [comment]
Awesome and much appreciated!
