### ISSUE TITLE
Error installing ghostToHugo

### ISSUE THREAD

**Issue by kirtan403** [jbarone/ghostToHugo#8]
I ran the following command to install: `go get github.com/jbarone/ghostToHugo`
Output is something like this: 
```
# github.com/jbarone/ghostToHugo/lib/hugo
C:\Users\dell\go\src\github.com\jbarone\ghostToHugo\lib\hugo\hugo.go:75: multiple-value hugolib.NewSiteDefaultLang() in single-value context
C:\Users\dell\go\src\github.com\jbarone\ghostToHugo\lib\hugo\hugo.go:137: undefined: helpers.AbsPathify
C:\Users\dell\go\src\github.com\jbarone\ghostToHugo\lib\hugo\hugo.go:141: undefined: helpers.AbsPathify
```

Not sure what's wrong. 

Using go 1.8 on windows 10 64-bit

**Comment by jbarone** [comment]
Well, that's no good. I'll look into it and get a fix up soon.

**Comment by jbarone** [comment]
Looks like I missed one.

**Comment by jbarone** [comment]
It should be working for you now. Please let me know if you're still having issues.

**Comment by kirtan403** [comment]
Thank you for the quick response. It worked. Awesome 👍
