### ISSUE TITLE
Date parsing issue with Ghost 009 export

### ISSUE THREAD

**Issue by julianxhokaxhiu** [jbarone/ghostToHugo#9]
Hi,

I was trying to use this super awesome tool to convert my Ghost export to Hugo, although I'm having a strange issue over dates.

Exported JSON:
```
{
  "db": [{
    "meta": {
      "exported_on": 1487969658983,
      "version": "009"
    },
    "data": {
      "posts": [{
        "id": 2,
        "uuid": "f3f0caa2-4a3b-4bc3-a76e-97c0f22e563e",
        "title": "Welcome",
        "slug": "welcome",
        "markdown": "<content>",
        "image": null,
        "featured": 0,
        "page": 0,
        "status": "published",
        "language": "en_US",
        "meta_title": null,
        "meta_description": null,
        "author_id": 1,
        "created_at": "2010-05-30 13:46:11",
        "created_by": 1,
        "updated_at": "2010-05-30 13:46:11",
        "updated_by": 1,
        "published_at": "2010-05-30 13:46:11",
        "published_by": 1,
        "visibility": "public",
        "mobiledoc": null,
        "amp": null
      }, ...
```

Output example:
```
author = "Julian Xhokaxhiu"
description = ""
slug = "welcome"
draft = false
title = "Welcome"
date = 0001-01-01T00:00:00Z
```

config.toml
```
languageCode = "en-us"
title = "My New Hugo Site"
baseurl = "http://example.org/"
```

go version
```
go version go1.8 linux/amd64
```

As you see `date` is completely ignored. I've tried to use the [`--dateformat`](https://github.com/jbarone/ghostToHugo/issues/3#issuecomment-239686721) option without success.

Any idea?

**Comment by jbarone** [comment]
hmm date format should work. Did you try `--dateformat "2006-01-02 15:04:05"`?

**Comment by julianxhokaxhiu** [comment]
Ok this is interesting. I thought that string was arbitrary string, but indeed if I use the one provided by you works fine.

Can you please add this to the README? Imho it was not clear.

Thank you very much and best regards :)

**Comment by jbarone** [comment]
Yeah, go uses some odd time/date format strings. I will happily update the ReadME. And, I'm glad to hear that it is working for you.
